default_context:
  project_name: 'news_summary_backend'
  project_slug: 'news-summary'
  domain_main: 'news-summary.rikkei.org'
  domain_staging: 'stag.news-summary.rikkei.org'
  docker_swarm_stack_name_main: 'news-summary-rikkei-org'
  docker_swarm_stack_name_staging: 'stag-news-summary-rikkei-org'
  secret_key: '123456a@'
  first_superuser: 'hungnv4@rikkeisoft.com'
  first_superuser_password: '123456a@'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.news-summary.rikkei.org", "https://stag.news-summary.rikkei.org", "https://news-summary.rikkei.org", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.gmail.com'
  smtp_user: 'hungnv4@rikkeisoft.com'
  smtp_password: 'TestPassword'
  smtp_emails_from_email: 'hungnv4@rikkeisoft.com'
  postgres_password: '123456a@'
  pgadmin_default_user: 'newsummary'
  pgadmin_default_user_password: '123456a@'
  traefik_constraint_tag: 'news-summary.rikkei.org'
  traefik_constraint_tag_staging: 'stag.news-summary.rikkei.org'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:123456a@'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
